branch-defaults:
  master:
    environment: sponzormewebprodenv
global:
  application_name: sponzormeweb
  default_ec2_keyname: sponzormestaging
  default_platform: PHP 5.6
  default_region: us-west-2
  profile: eb-cli
  sc: git